//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace premier_access_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movie()
        {
            this.premier_access = new HashSet<premier_access>();
        }
    
        public int id { get; set; }
        public string movie_name { get; set; }
        public System.DateTime movie_date { get; set; }
        public System.TimeSpan duration { get; set; }
        public string category { get; set; }
        public string studio { get; set; }
        public string director { get; set; }
        public string genre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<premier_access> premier_access { get; set; }
    }
}
