//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity_framework_example
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> age { get; set; }
        public int id_sex { get; set; }
    
        public virtual c_sex c_sex { get; set; }
    }
}
